export const groupmap = {
  1: 'https://xiaoying.tv/v/',
  2: 'https://asia.vivavideo.tv/v/',
  3: 'https://us.vivavideo.tv/v/',
  4: 'https://us.vivavideo.tv/v/',
  5: 'https://asia.vivavideo.tv/v/',
  6: 'https://meast.vivavideo.tv/v/',
  7: 'https://asia.vivavideo.tv/v/',
  8: 'https://asia.vivavideo.tv/v/',
  9: 'https://asia.vivavideo.tv/v/',
};
export const VIDEOTRACE = {
  10: '第一页的第一个位置',
  11: '上浮视频',
  12: '上浮晋级到曝光池',
  13: 'VCM推荐到曝光池',
  20: '冲榜视频',
  30: '白名单视频',
  40: '活动',
  50: '排行榜',
  60: '历史热门',
  70: '等级热门',
  71: '等级热门1',
  72: '等级热门2',
  73: '等级热门3',
  74: '等级热门4',
  75: '等级热门5',
  80: '爬取的视频，标签为143',
  85: '小剧本，标签142',
  90: 'status视频，标签为141',
  95: 'Youtube视频，标签为4,2,5',
  96: '标签视频',
  97: '标签热门视频',
  100: 'ODPS中分数高的视频',
  200: '根据等级热门和用户标签偏好生成',
  300: '根据等级热门和用户标签偏好生成',
  400: '等级热门',
};
export const LANGUAGE_MAP = {
  und: 'undefined',
  af: '南非语',
  sq: '阿尔巴尼亚语',
  am: '阿姆哈拉语',
  ar: '阿拉伯语',
  hy: '亚美尼亚语',
  az: '阿塞拜疆语',
  eu: '巴斯克语',
  be: '白俄罗斯语',
  bn: '孟加拉语',
  bs: '波斯尼亚语',
  bg: '保加利亚语',
  ca: '加泰罗尼亚语',
  ceb: '宿务语',
  'zh-CN': '中文（简体）',
  'zh-TW': '中文（繁体）',
  co: '科西嘉语',
  hr: '克罗地亚语',
  cs: '捷克语',
  da: '丹麦语',
  nl: '荷兰语',
  en: '英语',
  eo: '世界语',
  et: '爱沙尼亚语',
  fi: '芬兰语',
  fr: '法语',
  fy: '弗里斯兰语',
  gl: '加利西亚语',
  ka: '格鲁吉亚语',
  de: '德语',
  el: '希腊语',
  gu: '古吉拉特语',
  ht: '克里奥尔语',
  ha: '豪萨语',
  haw: '夏威夷语',
  iw: '希伯来语',
  hi: '印地语',
  hmn: '苗语',
  hu: '匈牙利语',
  is: '冰岛语',
  ig: '伊博语',
  id: '印度尼西亚语',
  ga: '爱尔兰语',
  it: '意大利语',
  ja: '日语',
  jw: '爪哇语',
  kn: '卡纳达语',
  kk: '哈萨克语',
  km: '高棉语',
  ko: '韩语',
  ku: '库尔德语',
  ky: '吉尔吉斯语',
  lo: '老挝语',
  la: '拉丁语',
  lv: '拉脱维亚语',
  lt: '立陶宛语',
  lb: '卢森堡语',
  mk: '马其顿语',
  mg: '马尔加什语',
  ms: '马来语',
  ml: '马拉雅拉姆语',
  mi: '毛利语',
  mr: '马拉地语',
  mn: '蒙古语',
  my: '缅甸语',
  ne: '尼泊尔语',
  no: '挪威语',
  ny: '奇切瓦语',
  ps: '普什图语',
  fa: '波斯语',
  pl: '波兰语',
  pt: '葡萄牙语',
  ma: '旁遮普语',
  ro: '罗马尼亚语',
  ru: '俄语',
  sm: '萨摩亚语',
  gd: '盖尔语',
  sr: '塞尔维亚语',
  st: '塞索托语',
  sn: '修纳语',
  sd: '信德语',
  si: '僧伽罗语',
  sk: '斯洛伐克语',
  sl: '斯洛文尼亚语',
  so: '索马里语',
  es: '西班牙语',
  su: '巽他语',
  sw: '斯瓦希里语',
  sv: '瑞典语',
  tl: '他加禄语',
  tg: '塔吉克语',
  ta: '泰米尔语',
  te: '泰卢固语',
  th: '泰语',
  tr: '土耳其语',
  uk: '乌克兰语',
  ur: '乌尔都语',
  uz: '乌兹别克语',
  vi: '越南语',
  cy: '威尔士语',
  xh: '科萨语',
  yi: '意第绪语',
  yo: '约鲁巴语',
  zu: '祖鲁语',
};

export const COUNTRY_SHOR_LIST = [
  { key: 'AD', value: '安道尔共和国' },
  { key: 'AE', value: '阿拉伯联合酋长国' },
  { key: 'AF', value: '阿富汗' },
  { key: 'AG', value: '安提瓜和巴布达' },
  { key: 'AI', value: '安圭拉岛' },
  { key: 'AL', value: '阿尔巴尼亚' },
  { key: 'AM', value: '阿美尼亚' },
  { key: 'AO', value: '安哥拉' },
  { key: 'AR', value: '阿根廷' },
  { key: 'AT', value: '奥地利' },
  { key: 'AU', value: '澳大利亚' },
  { key: 'AZ', value: '阿塞拜疆' },
  { key: 'BB', value: '巴巴多斯' },
  { key: 'BD', value: '孟加拉国' },
  { key: 'BE', value: '比利时' },
  { key: 'BF', value: '布基纳法索' },
  { key: 'BG', value: '保加利亚' },
  { key: 'BH', value: '巴林' },
  { key: 'BI', value: '布隆迪' },
  { key: 'BJ', value: '贝宁' },
  { key: 'BL', value: '巴勒斯坦' },
  { key: 'BM', value: '百慕大群岛' },
  { key: 'BN', value: '文莱' },
  { key: 'BO', value: '玻利维亚' },
  { key: 'BR', value: '巴西' },
  { key: 'BS', value: '巴哈马' },
  { key: 'BW', value: '博茨瓦纳' },
  { key: 'BY', value: '白俄罗斯' },
  { key: 'BZ', value: '伯利兹' },
  { key: 'CA', value: '加拿大' },
  { key: 'CF', value: '中非共和国' },
  { key: 'CG', value: '刚果' },
  { key: 'CH', value: '瑞士' },
  { key: 'CK', value: '库克群岛' },
  { key: 'CL', value: '智利' },
  { key: 'CM', value: '喀麦隆' },
  { key: 'CN', value: '中国' },
  { key: 'CO', value: '哥伦比亚' },
  { key: 'CR', value: '哥斯达黎加' },
  { key: 'CS', value: '捷克' },
  { key: 'CU', value: '古巴' },
  { key: 'CY', value: '塞浦路斯' },
  { key: 'CZ', value: '捷克' },
  { key: 'DE', value: '德国' },
  { key: 'DJ', value: '吉布提' },
  { key: 'DK', value: '丹麦' },
  { key: 'DO', value: '多米尼加共和国' },
  { key: 'DZ', value: '阿尔及利亚' },
  { key: 'EC', value: '厄瓜多尔' },
  { key: 'EE', value: '爱沙尼亚' },
  { key: 'EG', value: '埃及' },
  { key: 'ES', value: '西班牙' },
  { key: 'ET', value: '埃塞俄比亚' },
  { key: 'FI', value: '芬兰' },
  { key: 'FJ', value: '斐济' },
  { key: 'FR', value: '法国' },
  { key: 'GA', value: '加蓬' },
  { key: 'GB', value: '英国' },
  { key: 'GD', value: '格林纳达' },
  { key: 'GE', value: '格鲁吉亚' },
  { key: 'GF', value: '法属圭亚那' },
  { key: 'GH', value: '加纳' },
  { key: 'GI', value: '直布罗陀' },
  { key: 'GM', value: '冈比亚' },
  { key: 'GN', value: '几内亚' },
  { key: 'GR', value: '希腊' },
  { key: 'GT', value: '危地马拉' },
  { key: 'GU', value: '关岛' },
  { key: 'GY', value: '圭亚那' },
  { key: 'HK', value: '香港(中国)' },
  { key: 'HN', value: '洪都拉斯' },
  { key: 'HT', value: '海地' },
  { key: 'HU', value: '匈牙利' },
  { key: 'ID', value: '印度尼西亚' },
  { key: 'IE', value: '爱尔兰' },
  { key: 'IL', value: '以色列' },
  { key: 'IN', value: '印度' },
  { key: 'IQ', value: '伊拉克' },
  { key: 'IR', value: '伊朗' },
  { key: 'IS', value: '冰岛' },
  { key: 'IT', value: '意大利' },
  { key: 'JM', value: '牙买加' },
  { key: 'JO', value: '约旦' },
  { key: 'JP', value: '日本' },
  { key: 'KE', value: '肯尼亚' },
  { key: 'KG', value: '吉尔吉斯坦' },
  { key: 'KH', value: '柬埔寨' },
  { key: 'KP', value: '朝鲜' },
  { key: 'KR', value: '韩国' },
  { key: 'KT', value: '科特迪瓦共和国' },
  { key: 'KW', value: '科威特' },
  { key: 'KZ', value: '哈萨克斯坦' },
  { key: 'LA', value: '老挝' },
  { key: 'LB', value: '黎巴嫩' },
  { key: 'LC', value: '圣卢西亚' },
  { key: 'LI', value: '列支敦士登' },
  { key: 'LK', value: '斯里兰卡' },
  { key: 'LR', value: '利比里亚' },
  { key: 'LS', value: '莱索托' },
  { key: 'LT', value: '立陶宛' },
  { key: 'LU', value: '卢森堡' },
  { key: 'LV', value: '拉脱维亚' },
  { key: 'LY', value: '利比亚' },
  { key: 'MA', value: '摩洛哥' },
  { key: 'MC', value: '摩纳哥' },
  { key: 'MD', value: '摩尔多瓦' },
  { key: 'MG', value: '马达加斯加' },
  { key: 'ML', value: '马里' },
  { key: 'MM', value: '缅甸' },
  { key: 'MN', value: '蒙古' },
  { key: 'MO', value: '澳门（中国）' },
  { key: 'MS', value: '蒙特塞拉特岛' },
  { key: 'MT', value: '马耳他' },
  { key: 'MU', value: '毛里求斯' },
  { key: 'MV', value: '马尔代夫' },
  { key: 'MW', value: '马拉维' },
  { key: 'MX', value: '墨西哥' },
  { key: 'MY', value: '马来西亚' },
  { key: 'MZ', value: '莫桑比克' },
  { key: 'NA', value: '纳米比亚' },
  { key: 'NE', value: '尼日尔' },
  { key: 'NG', value: '尼日利亚' },
  { key: 'NI', value: '尼加拉瓜' },
  { key: 'NL', value: '荷兰' },
  { key: 'NO', value: '挪威' },
  { key: 'NP', value: '尼泊尔' },
  { key: 'NR', value: '瑙鲁' },
  { key: 'NZ', value: '新西兰' },
  { key: 'OM', value: '阿曼' },
  { key: 'PA', value: '巴拿马' },
  { key: 'PE', value: '秘鲁' },
  { key: 'PF', value: '法属玻利尼西亚' },
  { key: 'PG', value: '巴布亚新几内亚' },
  { key: 'PH', value: '菲律宾' },
  { key: 'PK', value: '巴基斯坦' },
  { key: 'PL', value: '波兰' },
  { key: 'PR', value: '波多黎各' },
  { key: 'PT', value: '葡萄牙' },
  { key: 'PY', value: '巴拉圭' },
  { key: 'QA', value: '卡塔尔' },
  { key: 'RO', value: '罗马尼亚' },
  { key: 'RU', value: '俄罗斯' },
  { key: 'SA', value: '沙特阿拉伯' },
  { key: 'SB', value: '所罗门群岛' },
  { key: 'SC', value: '塞舌尔' },
  { key: 'SD', value: '苏丹' },
  { key: 'SE', value: '瑞典' },
  { key: 'SG', value: '新加坡' },
  { key: 'SI', value: '斯洛文尼亚' },
  { key: 'SK', value: '斯洛伐克' },
  { key: 'SL', value: '塞拉利昂' },
  { key: 'SM', value: '圣马力诺' },
  { key: 'SN', value: '塞内加尔' },
  { key: 'SO', value: '索马里' },
  { key: 'SR', value: '苏里南' },
  { key: 'ST', value: '圣多美和普林西比' },
  { key: 'SV', value: '萨尔瓦多' },
  { key: 'SY', value: '叙利亚' },
  { key: 'SZ', value: '斯威士兰' },
  { key: 'TD', value: '乍得' },
  { key: 'TG', value: '多哥' },
  { key: 'TH', value: '泰国' },
  { key: 'TJ', value: '塔吉克斯坦' },
  { key: 'TM', value: '土库曼斯坦' },
  { key: 'TN', value: '突尼斯' },
  { key: 'TO', value: '汤加' },
  { key: 'TR', value: '土耳其' },
  { key: 'TT', value: '特立尼达和多巴哥' },
  { key: 'TW', value: '台湾（中国）' },
  { key: 'TZ', value: '坦桑尼亚' },
  { key: 'UA', value: '乌克兰' },
  { key: 'UG', value: '乌干达' },
  { key: 'US', value: '美国' },
  { key: 'UY', value: '乌拉圭' },
  { key: 'UZ', value: '乌兹别克斯坦' },
  { key: 'VC', value: '圣文森特岛' },
  { key: 'VE', value: '委内瑞拉' },
  { key: 'VN', value: '越南' },
  { key: 'YE', value: '也门' },
  { key: 'YU', value: '南斯拉夫' },
  { key: 'ZA', value: '南非' },
  { key: 'ZM', value: '赞比亚' },
  { key: 'ZR', value: '扎伊尔' },
  { key: 'ZW', value: '津巴布韦' },
];

export const COUNTRY_MAP = {
  AD: '安道尔共和国',
  AE: '阿拉伯联合酋长国',
  AF: '阿富汗',
  AG: '安提瓜和巴布达',
  AI: '安圭拉岛',
  AL: '阿尔巴尼亚',
  AM: '阿美尼亚',
  AO: '安哥拉',
  AR: '阿根廷',
  AT: '奥地利',
  AU: '澳大利亚',
  AZ: '阿塞拜疆',
  BB: '巴巴多斯',
  BD: '孟加拉国',
  BE: '比利时',
  BF: '布基纳法索',
  BG: '保加利亚',
  BH: '巴林',
  BI: '布隆迪',
  BJ: '贝宁',
  BL: '巴勒斯坦',
  BM: '百慕大群岛',
  BN: '文莱',
  BO: '玻利维亚',
  BR: '巴西',
  BS: '巴哈马',
  BW: '博茨瓦纳',
  BY: '白俄罗斯',
  BZ: '伯利兹',
  CA: '加拿大',
  CF: '中非共和国',
  CG: '刚果',
  CH: '瑞士',
  CK: '库克群岛',
  CL: '智利',
  CM: '喀麦隆',
  CN: '中国',
  CO: '哥伦比亚',
  CR: '哥斯达黎加',
  CS: '捷克',
  CU: '古巴',
  CY: '塞浦路斯',
  CZ: '捷克',
  DE: '德国',
  DJ: '吉布提',
  DK: '丹麦',
  DO: '多米尼加共和国',
  DZ: '阿尔及利亚',
  EC: '厄瓜多尔',
  EE: '爱沙尼亚',
  EG: '埃及',
  ES: '西班牙',
  ET: '埃塞俄比亚',
  FI: '芬兰',
  FJ: '斐济',
  FR: '法国',
  GA: '加蓬',
  GB: '英国',
  GD: '格林纳达',
  GE: '格鲁吉亚',
  GF: '法属圭亚那',
  GH: '加纳',
  GI: '直布罗陀',
  GM: '冈比亚',
  GN: '几内亚',
  GR: '希腊',
  GT: '危地马拉',
  GU: '关岛',
  GY: '圭亚那',
  HK: '香港(中国)',
  HN: '洪都拉斯',
  HT: '海地',
  HU: '匈牙利',
  ID: '印度尼西亚',
  IE: '爱尔兰',
  IL: '以色列',
  IN: '印度',
  IQ: '伊拉克',
  IR: '伊朗',
  IS: '冰岛',
  IT: '意大利',
  JM: '牙买加',
  JO: '约旦',
  JP: '日本',
  KE: '肯尼亚',
  KG: '吉尔吉斯坦',
  KH: '柬埔寨',
  KP: '朝鲜',
  KR: '韩国',
  KT: '科特迪瓦共和国',
  KW: '科威特',
  KZ: '哈萨克斯坦',
  LA: '老挝',
  LB: '黎巴嫩',
  LC: '圣卢西亚',
  LI: '列支敦士登',
  LK: '斯里兰卡',
  LR: '利比里亚',
  LS: '莱索托',
  LT: '立陶宛',
  LU: '卢森堡',
  LV: '拉脱维亚',
  LY: '利比亚',
  MA: '摩洛哥',
  MC: '摩纳哥',
  MD: '摩尔多瓦',
  MG: '马达加斯加',
  ML: '马里',
  MM: '缅甸',
  MN: '蒙古',
  MO: '澳门（中国）',
  MS: '蒙特塞拉特岛',
  MT: '马耳他',
  MU: '毛里求斯',
  MV: '马尔代夫',
  MW: '马拉维',
  MX: '墨西哥',
  MY: '马来西亚',
  MZ: '莫桑比克',
  NA: '纳米比亚',
  NE: '尼日尔',
  NG: '尼日利亚',
  NI: '尼加拉瓜',
  NL: '荷兰',
  NO: '挪威',
  NP: '尼泊尔',
  NR: '瑙鲁',
  NZ: '新西兰',
  OM: '阿曼',
  PA: '巴拿马',
  PE: '秘鲁',
  PF: '法属玻利尼西亚',
  PG: '巴布亚新几内亚',
  PH: '菲律宾',
  PK: '巴基斯坦',
  PL: '波兰',
  PR: '波多黎各',
  PT: '葡萄牙',
  PY: '巴拉圭',
  QA: '卡塔尔',
  RO: '罗马尼亚',
  RU: '俄罗斯',
  SA: '沙特阿拉伯',
  SB: '所罗门群岛',
  SC: '塞舌尔',
  SD: '苏丹',
  SE: '瑞典',
  SG: '新加坡',
  SI: '斯洛文尼亚',
  SK: '斯洛伐克',
  SL: '塞拉利昂',
  SM: '圣马力诺',
  SN: '塞内加尔',
  SO: '索马里',
  SR: '苏里南',
  ST: '圣多美和普林西比',
  SV: '萨尔瓦多',
  SY: '叙利亚',
  SZ: '斯威士兰',
  TD: '乍得',
  TG: '多哥',
  TH: '泰国',
  TJ: '塔吉克斯坦',
  TM: '土库曼斯坦',
  TN: '突尼斯',
  TO: '汤加',
  TR: '土耳其',
  TT: '特立尼达和多巴哥',
  TW: '台湾（中国）',
  TZ: '坦桑尼亚',
  UA: '乌克兰',
  UG: '乌干达',
  US: '美国',
  UY: '乌拉圭',
  UZ: '乌兹别克斯坦',
  VC: '圣文森特岛',
  VE: '委内瑞拉',
  VN: '越南',
  YE: '也门',
  YU: '南斯拉夫',
  ZA: '南非',
  ZM: '赞比亚',
  ZR: '扎伊尔',
  ZW: '津巴布韦',
};
